version: '3.0'

services:
  frontend:
    container_name: transfer_service_frontend
    build: ./frontend
    image: 'frontend:latest'
    ports:
      - '3000:3000'

  backend:
    container_name: transfer_service_backend
    build: ./
    image: 'backend:latest'
    ports:
      - '8080:8080'